# Development

name = "nft-storage-dev"
account_id = "fffa4b4363a7e5250af8357087263b3a"
workers_dev = true
type = "javascript"

# Compatibility flags https://github.com/cloudflare/wrangler/pull/2009
compatibility_date = "2021-08-23"
compatibility_flags = [ "formdata_parser_supports_files" ]

[vars]
ENV = "dev"
DEBUG = "true"
DATABASE_URL = "https://ryoouiwnemjhenyqqlhp.supabase.co/rest/v1"

[build]
command = "scripts/cli.js build"
watch_dir = "src"

[build.upload]
format = "service-worker"

# Staging

[env.staging]
name = "nft-storage-staging"
route = "api-staging.nft.storage/*"
zone_id = "fc6cb51dbc2d0b9a729eae6a302a49c9"
usage_model = "unbound"

[env.staging.vars]
ENV = "staging"
DEBUG = "true"
DATABASE_URL = "https://nft-storage-pgrest-staging.herokuapp.com"

[env.staging.build]
command = "scripts/cli.js build --env staging"
watch_dir = "src"

[env.staging.build.upload]
format = "service-worker"

# Production

[env.production]
name = "nft-storage"
route = "api.nft.storage/*"
zone_id = "fc6cb51dbc2d0b9a729eae6a302a49c9"
usage_model = "unbound"

[env.production.vars]
ENV = "production"
DEBUG = "false"
DATABASE_URL = "https://nft-storage-pgrest-prod.herokuapp.com"

[env.production.build]
command = "scripts/cli.js build --env production"
watch_dir = "src"

[env.production.build.upload]
format = "service-worker"

# Dev accounts

[env.alanshaw]
name = "nft-storage-alanshaw"
account_id = "4fe12d085474d33bdcfd8e9bed4d8f95"
workers_dev = true
route = ""
zone_id = ""

[env.alanshaw.vars]
ENV = "dev"
DEBUG = "*"
CLUSTER_API_URL = "https://alan-cluster-api-nft-storage.loca.lt"
CLUSTER_ADDRS = ""
DATABASE_URL = "https://alan-postgrest-nft-storage.loca.lt"

[env.gozala]
name="nft-storage-gozala"
account_id="fffa4b4363a7e5250af8357087263b3a"
workers_dev = true
usage_model="bundled"
route = ""
zone_id = ""

[env.gozala.vars]
ENV = "dev"
DEBUG = "*"
CLUSTER_API_URL = "https://nft.storage.ipfscluster.io/api/"
CLUSTER_ADDRS = ""
DATABASE_URL = "http://localhost:8000"

[env.ze]
type = "webpack"
name = "nft-storage-ze"
account_id = "9357c50891f315d3c8a84e87ee47f740"
workers_dev = true
usage_model = ""
route = ""
zone_id = ""

[env.ze.vars]
ENV = "dev"
DEBUG = "*"
CLUSTER_API_URL = "https://ze-cluster-api-nft-storage.loca.lt"
CLUSTER_ADDRS = ""
DATABASE_URL = "http://localhost:8000"

[env.yusef]
name = "nft-storage-yusef"
account_id = "8c3da25233263bd7a26c0e2e04569ded"
workers_dev = true
route = ""
zone_id = ""

[env.yusef.vars]
ENV = "dev"
DEBUG = "*"
CLUSTER_API_URL = "https://yusef-cluster-api-nft-storage.loca.lt"
DATABASE_URL = "https://yusef-postgrest-nft-storage.loca.lt"

[env.redaphid]
workers_dev = true
account_id = "2f1143f469f762af4ef2336ec13f85b7"

[env.redaphid.vars]
ENV = "dev"
DEBUG = "*"
CLUSTER_API_URL = "https://redaphid-cluster-api-nft-storage.loca.lt/"
DATABASE_URL = "https://redaphid-postgrest-nft-storage.loca.lt"

[env.vsantos]
name = "nft-storage-vsantos"
account_id = "7ec0b7cf2ec201b2580374e53ba5f37b"
workers_dev = true
route = ""
zone_id = ""

[env.vsantos.vars]
ENV = "dev"
DEBUG = "*"
CLUSTER_API_URL = "https://vascosantos-cluster-api-nft-storage.loca.lt"
CLUSTER_ADDRS = ""
DATABASE_URL = "https://vascosantos-postgrest-nft-storage.loca.lt"