name: API
on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
      - '.github/workflows/api.yml'
  pull_request:
    paths:
      - 'packages/api/**'
      - '.github/workflows/api.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: bahmutov/npm-install@v1
      - run: npx playwright install-deps
      - run: yarn test:api
        env:
          DATABASE_URL: http://localhost:3000
          DATABASE_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsImlhdCI6MTYwMzk2ODgzNCwiZXhwIjoyNTUwNjUzNjM0LCJyb2xlIjoic2VydmljZV9yb2xlIn0.necIJaiP7X2T2QjGeV-FhpkizcNTX8HjDDBAxpgQTEI
          DATABASE_CONNECTION: postgresql://postgres:postgres@localhost:5432/postgres
          # DAG_CARGO_HOST: ${{secrets.DAG_CARGO_HOST}}
          # DAG_CARGO_DATABASE: ${{secrets.DAG_CARGO_DATABASE}}
          # DAG_CARGO_USER: ${{secrets.DAG_CARGO_USER}}
          # DAG_CARGO_PASSWORD: ${{secrets.DAG_CARGO_PASSWORD}}
  deploy-dev:
    name: Deploy Dev
    if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: bahmutov/npm-install@v1
      - name: Publish app
        uses: cloudflare/wrangler-action@1.3.0
        env:
          SENTRY_TOKEN: ${{secrets.SENTRY_TOKEN}}
        with:
          apiToken: ${{secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/api'
  deploy-staging:
    name: Deploy Staging
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: bahmutov/npm-install@v1
      - name: Publish app
        uses: cloudflare/wrangler-action@1.3.0
        env:
          SENTRY_TOKEN: ${{secrets.SENTRY_TOKEN}}
        with:
          apiToken: ${{secrets.CF_API_TOKEN }}
          workingDirectory: 'packages/api'
          environment: 'staging'
